version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    # restart: always
    network_mode: host
    ports:
    - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            database: c4c
            uri: 'mongodb://admin:admin@localhost:27017'